apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pbenches.pbench.cloudbulldozer.io
spec:
  group: pbench.cloudbulldozer.io
  names:
    kind: Pbench
    listKind: PbenchList
    plural: pbenches
    singular: pbench
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
