apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbench-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pbench-monitoring
  template:
    metadata:
      labels:
        name: pbench-monitoring
    spec:
      serviceAccountName: pbench-monitoring
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: quay.io/cloud-bulldozer/pbench-monitoring/:master
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: quay.io/cloud-bulldozer/pbench-monitoring/:master
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pbench-monitoring"
            - name: ANSIBLE_VERBOSITY
              value: "4"
        - name: redis-master
          image: k8s.gcr.io/redis:v1
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      volumes:
        - name: runner
          emptyDir: {}
