kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pbench-monitoring
subjects:
- kind: ServiceAccount
  name: pbench-monitoring
roleRef:
  kind: Role
  name: pbench-monitoring
  apiGroup: rbac.authorization.k8s.io
